version: "3.9"
services:
  app:
    build: ./infra/dev/php
    volumes:
      - ./src:/data
  web:
    image: nginx:1.20-alpine
    volumes:
      - ./src:/data
      - ./infra/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
